version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-thietbicongnghe
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: thietbicongnghe

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-thietbicongnghe

    restart: always

    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - "8081:80"

  backend:

    build: .

    container_name: backend-thietbicongnghe

    restart: always

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/thietbicongnghe
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  mysql_data: