name: Spring Boot CI-CD (Self Hosted VM)

on:
  push:
    branches: [ main ]

jobs:

  # ================= CI (GitHub)
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Maven
        run: mvn clean package -DskipTests


  # ================= CD (VM SELF-HOSTED)
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/vboxuser/thietbicongnghe
          git pull origin main

      - name: Build & Deploy Docker
        run: |
          docker compose down
          docker compose up -d --build